# Generated by Django 3.1.6 on 2021-02-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taizhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=32, verbose_name='设备名称')),
                ('device_model', models.CharField(max_length=64, verbose_name='设备型号')),
                ('device_range', models.CharField(max_length=64, verbose_name='量程')),
                ('device_precision', models.CharField(max_length=64, verbose_name='精度')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='制造商')),
                ('Commissioning_date', models.DateTimeField(blank=True, null=True, verbose_name='启用日期')),
                ('device_number', models.CharField(max_length=128, verbose_name='设备编号')),
                ('device_factory_number', models.CharField(max_length=128, unique=True, verbose_name='本厂编号')),
                ('calibration_department', models.SmallIntegerField(choices=[(0, '公司'), (1, '特种'), (2, '宜昌'), (3, '宜都'), (4, '广东'), (5, '广电')], default=0, verbose_name='检定部门')),
                ('calibration_cycle', models.SmallIntegerField(choices=[(0, '公司'), (1, '特种'), (2, '宜昌'), (3, '宜都'), (4, '广东'), (5, '广电')], default=1, verbose_name='检定周期')),
                ('calibration_time', models.DateTimeField(blank=True, null=True, verbose_name='检定日期')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='到期日期')),
                ('jieguo_type', models.CharField(max_length=20, verbose_name='检定结果')),
                ('device_type', models.SmallIntegerField(choices=[(0, 'B类'), (1, 'A类'), (2, 'C类')], default=0, verbose_name='设备类型')),
                ('device_user_department', models.SmallIntegerField(choices=[(0, '设备科'), (1, '环保科'), (2, '生产计划科'), (3, '信息科'), (4, '技术科'), (5, '质量科')], default=1, verbose_name='所属部门')),
                ('node', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
        ),
    ]
