# Generated by Django 3.1.6 on 2021-02-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shebei_guanli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taizhang',
            name='id',
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='device_factory_number',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='本厂编号'),
        ),
    ]
