# Generated by Django 3.1.6 on 2021-02-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shebei_guanli', '0003_auto_20210213_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taizhang',
            name='Commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='启用日期'),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='calibration_time',
            field=models.DateField(blank=True, null=True, verbose_name='检定日期'),
        ),
        migrations.AlterField(
            model_name='taizhang',
            name='expire_time',
            field=models.DateField(blank=True, null=True, verbose_name='到期日期'),
        ),
    ]
