# Generated by Django 3.1.6 on 2021-02-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shebei_guanli', '0004_auto_20210213_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
