# Generated by Django 3.1.6 on 2021-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shebei_guanli', '0004_auto_20210228_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='meiyuewanchengshu',
            name='now_year',
            field=models.CharField(default='/', max_length=32, unique=True),
        ),
    ]
