# Generated by Django 3.1.6 on 2021-02-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shebei_guanli', '0005_userdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdate',
        ),
    ]
